### ISSUE TITLE
404 kapot

### ISSUE THREAD

**Issue by eMPee584** [fsfw-dresden/git-ws#13]
`Das Material (Folien und Befehlsübersicht) gibt es unter http://fsfw-dresden.de/git-ws`

nicht :cry:

**Comment by cknoll** [comment]
Danke für den Hinweis.

@sebastianriese könntest Du das fixen?

fsfw-dresden.de/git-ws -> https://wiki.fsfw-dresden.de/doku.php/doku/git-workshop

**Comment by sebastianriese** [comment]
Ist repariert.
