### ISSUE TITLE
Inhalt: wir brauchen ein schönes Übungs-Repo

### ISSUE THREAD

**Issue by cknoll** [fsfw-dresden/git-ws#3]
- Es sollte nicht zu viele und nicht zu wenige commits haben (vielleicht so 5-10)
- Inhalt und Änderungen sollten nicht komplett foo-bar-trivial sein, aber auch nicht ablenken (vielleicht kurze Gedichte, wo man mit jedem commit eine Strophe hinzufügt)
- Anwendungsfall für branches sollte nachvollziehbar sein
- vorbereiteter merge-Konflikt wäre vielleicht auch nicht schlecht

siehe auch: https://github.com/githubtraining

@sebastianriese Ideen und Meinungen willkommen

**Comment by sebastianriese** [comment]
Idee: Der Gegenstand des Repos werden Shakespeare-Sonette (mit modifikationen für die Konflikte).

**Comment by Nos-** [comment]
Schöne Idee.

**Comment by cknoll** [comment]
ist schon länger eingebaut.
